### ISSUE TITLE
Dashboard does not start after PR#21

### ISSUE THREAD

**Issue by Yadunund** [osrf/romi-dashboard#28] opened 2020-05-26 09:27 UTC
Following the merge of #21, starting the dashboard with a live backend leaves the browser in this state until shutdown.
 
![image](https://user-images.githubusercontent.com/13482049/82884245-12e24f00-9f76-11ea-9f1c-27243ea5f8f0.png)

**Comment by baviera08** [comment] 2020-05-26 22:21
Error: 

```
[2020-05-26 16:24:04] [connect] WebSocket Connection [::ffff:127.0.0.1]:51342 v13 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" / 101
[soss::weboscket::Server] opened connection [0x7f7acc000b30]
[soss::websocket] Received subscription request for a topic that we are not currently advertising [dispenser_states]
```

**Comment by baviera08** [comment] 2020-05-27 21:58
As you know I was able to run the backend. I was running it with this version of `traffic_editor` (commit 4b77d415f36dfda06e8b48d6754589eb2bec9545 from May 21, 2020)

This is a summary of what we have on the interface:
* Robots following the path correctly
* Robot path displaying correctly
* Door state showing up correctly (it has bad coordinates with this version of traffic_editor). I hardcoded some coordinates to prove that.
![dorrs](https://user-images.githubusercontent.com/11761240/83075480-ef84d600-a041-11ea-8ec3-dcfede215866.gif)
* We didn't have any elevator on this version of `traffic_editor` yet.
* Request doors and lift were failing. When I requested a door to open I got this error on the soss console  `Segmentation fault (core dumped)`

Later, I updated the `traffic_editor` project to the last versions. After that, I wasn't able to enter to the dashboard. I got this error: 
```
Uncaught TypeError: missing key "door_name"
    at Function.fromObject (romi-js-core-interfaces.js:1)
    at romi-js-core-interfaces.js:1
    at Array.map (<anonymous>)
    at Function.fromObject (romi-js-core-interfaces.js:1)
    at romi-js-core-interfaces.js:1
    at Array.map (<anonymous>)
    at Function.fromObject (romi-js-core-interfaces.js:1)
    at Function.fromObject (romi-js-core-interfaces.js:1)
    at Object.validateResponse (romi-js-core-interfaces.js:1)
    at e._next (romi-js-soss-transport.js:16)
    at e.__tryOrUnsub (romi-js-soss-transport.js:16)
    at e.next (romi-js-soss-transport.js:16)
    at e._next (romi-js-soss-transport.js:16)
    at e.next (romi-js-soss-transport.js:16)
    at e._next (romi-js-soss-transport.js:16)
    at e.next (romi-js-soss-transport.js:16)
    at e._next (romi-js-soss-transport.js:16)
    at e.next (romi-js-soss-transport.js:16)
    at e.next (romi-js-soss-transport.js:16)
    at WebSocket.f.onmessage (romi-js-soss-transport.js:16)
```

I guess it can be fixed with a new release of `romi-js-core-interfaces`. What's happening, and correct me if I'm wrong, is the following when the dashboard starts it tries to subscribe to the `buildingMap` that has the door.msg. The door.msg is in an old version on `romi-js-soss-transport` (with the two names, name and door_name), so the romi-js-soss-transport tries to map its door.msg to the new one (where the door_name is missing), and that its breaking all.

**Comment by koonpeng** [comment] 2020-05-28 00:45
> These are the only messages in the terminal running soss:

This probably means the soss config is not set up to serve those messages, adding 
```
dispenser_states: { type: "rmf_dispenser_msgs/DispenserState", route: ros2_to_client }
```
along with any other needed messages should fix it. Its likely to be introduced when the dispenser information is merged in and the soss config is never updated.

> I guess it can be fixed with a new release of romi-js-core-interfaces. What's happening, and correct me if I'm wrong, is the following when the dashboard starts it tries to subscribe to the buildingMap that has the door.msg. The door.msg is in an old version on romi-js-soss-transport (with the two names, name and door_name), so the romi-js-soss-transport tries to map its door.msg to the new one (where the door_name is missing), and that its breaking all.

Yes, that looks to be exactly whats happening, changing it to use `name` instead of `door_name` should fix it.

I guess these issues show the need for an e2e tests to catch them early.

**Comment by baviera08** [comment] 2020-05-28 01:55
> > These are the only messages in the terminal running soss:
> 
> This probably means the soss config is not set up to serve those messages, adding
> 
> ```
> dispenser_states: { type: "rmf_dispenser_msgs/DispenserState", route: ros2_to_client }
> ```
> 
> along with any other needed messages should fix it. Its likely to be introduced when the dispenser information is merged in and the soss config is never updated.
> 
> > I guess it can be fixed with a new release of romi-js-core-interfaces. What's happening, and correct me if I'm wrong, is the following when the dashboard starts it tries to subscribe to the buildingMap that has the door.msg. The door.msg is in an old version on romi-js-soss-transport (with the two names, name and door_name), so the romi-js-soss-transport tries to map its door.msg to the new one (where the door_name is missing), and that its breaking all.
> 
> Yes, that looks to be exactly whats happening, updating to the latest version should fix it.
> 
> I guess these issues show the need for an e2e tests to catch them early.

Yeah, you're right. Thanks for the feedback.

**Comment by koonpeng** [comment] 2020-05-28 08:31
> Request doors and lift were failing. When I requested a door to open I got this error on the soss console Segmentation fault (core dumped)

I found the cause of this, see https://github.com/osrf/soss/issues/36. Particularly, it fails while converting `builtin_interfaces/Time` as this is the definition

```
int32 sec
uint32 nanosec
```

conversion of `int32` fails because of above bug.

**Closed** 2020-05-28 14:39 UTC

**Comment by baviera08** [comment] 2020-05-28 14:45
> > Request doors and lift were failing. When I requested a door to open I got this error on the soss console Segmentation fault (core dumped)
> 
> I found the cause of this, see [osrf/soss#36](https://github.com/osrf/soss/issues/36). Particularly, it fails while converting `builtin_interfaces/Time` as this is the definition
> 
> ```
> int32 sec
> uint32 nanosec
> ```
> 
> conversion of `int32` fails because of above bug.

Thanks a lot for looking into that.
